### PR TITLE
Bump Node to 13.12.0

### PR DESCRIPTION
**Pull request by w1gz**
https://github.com/fretlink/app/issues/3613.

### CODE REVIEW

**Comment by w1gz** [comment]
Tested locally, it builds :ok_hand:.

**Review by paulrbr-fl — COMMENTED** [review]
Looks good, would you mind bumping the mongo source list [(from 3.6 to 4.0)](https://github.com/fretlink/infrastructure/issues/916) too please?

**Comment by w1gz** [comment]
Yep, bump is currently in testing locally :+1:

**Comment by w1gz** [comment]
Everything is good locally :tada:.

**Comment by paulrbr-fl** [comment]
Nice thanks for the changes. Don't forget to release → https://github.com/fretlink/docker-node-mongotools/releases

**Pull request merged**
